//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jakub.Skoczen.PrescriptionGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jakub.Skoczen.PrescriptionGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę podac datę urodzenia.
        /// </summary>
        internal static string BirthDateError {
            get {
                return ResourceManager.GetString("BirthDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać choroby przewlekłe.
        /// </summary>
        internal static string ChronicDiseasesError {
            get {
                return ResourceManager.GetString("ChronicDiseasesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę podać dane lekarza.
        /// </summary>
        internal static string DoctorsIdError {
            get {
                return ResourceManager.GetString("DoctorsIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać nazwisko.
        /// </summary>
        internal static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać miejscowość.
        /// </summary>
        internal static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać imię.
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę podać oddział NFZ.
        /// </summary>
        internal static string NFZBranchError {
            get {
                return ResourceManager.GetString("NFZBranchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę podać uprawnienai.
        /// </summary>
        internal static string PermissionsError {
            get {
                return ResourceManager.GetString("PermissionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać poprawny pesel.
        /// </summary>
        internal static string PeselError {
            get {
                return ResourceManager.GetString("PeselError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać treść recepty.
        /// </summary>
        internal static string PrescriptionError {
            get {
                return ResourceManager.GetString("PrescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisać datę od której recepta obowiązuje.
        /// </summary>
        internal static string RealizationFromDateError {
            get {
                return ResourceManager.GetString("RealizationFromDateError", resourceCulture);
            }
        }
    }
}
